// AUTO-GENERATED companion data for SymbolIcon's Android (Material Symbols) path.
// Regenerate by re-running the font build script if the icon vocabulary changes.
// Each SF Symbol name used anywhere in the app maps to a Material Symbols glyph;
// `filled` selects the Filled face (assets/fonts/MaterialSymbolsFilled.ttf) over
// the Outlined one. Codepoints index the subset fonts bundled in assets/fonts.

export type MaterialGlyph = { md: string; filled: boolean }

/** Codepoint for every Material Symbols glyph bundled in the subset fonts. */
export const MATERIAL_CODEPOINTS: Record<string, number> = {
  add: 0xe145,
  arrow_circle_down: 0xf181,
  book: 0xe86e,
  calendar_today: 0xe935,
  cancel: 0xe888,
  check: 0xe668,
  check_circle: 0xf0be,
  chevron_left: 0xe5cb,
  chevron_right: 0xe5cc,
  close: 0xe5cd,
  content_copy: 0xe14d,
  contrast: 0xeb37,
  delete: 0xe92e,
  description: 0xe873,
  edit: 0xf097,
  edit_square: 0xf88d,
  expand_less: 0xe5ce,
  expand_more: 0xe5cf,
  favorite: 0xe87e,
  filter_list: 0xe152,
  graphic_eq: 0xe1b8,
  group: 0xea21,
  handyman: 0xf10b,
  help: 0xe8fd,
  image: 0xe3f4,
  info: 0xe88e,
  language: 0xea07,
  library_add: 0xe03c,
  link: 0xe250,
  list: 0xe896,
  local_fire_department: 0xef55,
  lock: 0xe899,
  mail: 0xe159,
  menu: 0xe5d2,
  menu_book: 0xea19,
  mic_off: 0xe02b,
  more_horiz: 0xe5d3,
  music_note: 0xe405,
  notifications: 0xe7f5,
  person: 0xf0d3,
  piano: 0xe521,
  queue_music: 0xe03d,
  remove: 0xe15b,
  schedule: 0xefd6,
  search: 0xef7a,
  send: 0xe163,
  sensors: 0xe51e,
  share: 0xe80d,
  star: 0xf09a,
  sync: 0xe627,
  touch_app: 0xe913,
  unfold_more: 0xe5d7,
  visibility: 0xe8f4,
  visibility_off: 0xe8f5,
  warning: 0xf083,
  wifi_off: 0xe648,
}

/**
 * Maps each SF Symbol name in use to its Android (Material Symbols) equivalent.
 * SF names ending in `.fill` render with the Filled face; a handful of glyphs
 * (heart, star, group, check_circle, warning, send, cancel, flame) share one
 * Material name across their outline/fill SF variants and differ only by `filled`.
 */
export const SF_TO_MATERIAL: Record<string, MaterialGlyph> = {
  'antenna.radiowaves.left.and.right': { md: 'sensors', filled: false },
  'arrow.down.circle': { md: 'arrow_circle_down', filled: false },
  'arrow.triangle.2.circlepath': { md: 'sync', filled: false },
  'bell': { md: 'notifications', filled: false },
  'book': { md: 'menu_book', filled: false },
  'book.closed': { md: 'book', filled: false },
  'calendar': { md: 'calendar_today', filled: false },
  'checkmark': { md: 'check', filled: false },
  'checkmark.circle.fill': { md: 'check_circle', filled: true },
  'chevron.down': { md: 'expand_more', filled: false },
  'chevron.left': { md: 'chevron_left', filled: false },
  'chevron.right': { md: 'chevron_right', filled: false },
  'chevron.up': { md: 'expand_less', filled: false },
  'chevron.up.chevron.down': { md: 'unfold_more', filled: false },
  'circle.lefthalf.filled': { md: 'contrast', filled: false },
  'clock': { md: 'schedule', filled: false },
  'doc.on.doc': { md: 'content_copy', filled: false },
  'doc.text': { md: 'description', filled: false },
  'ellipsis': { md: 'more_horiz', filled: false },
  'envelope': { md: 'mail', filled: false },
  'exclamationmark.triangle.fill': { md: 'warning', filled: true },
  'eye': { md: 'visibility', filled: false },
  'eye.slash': { md: 'visibility_off', filled: false },
  'flame.fill': { md: 'local_fire_department', filled: true },
  'globe': { md: 'language', filled: false },
  'hand.tap': { md: 'touch_app', filled: false },
  'heart': { md: 'favorite', filled: false },
  'heart.fill': { md: 'favorite', filled: true },
  'info.circle': { md: 'info', filled: false },
  'line.3.horizontal': { md: 'menu', filled: false },
  'line.3.horizontal.decrease': { md: 'filter_list', filled: false },
  'link': { md: 'link', filled: false },
  'list.bullet': { md: 'list', filled: false },
  'lock': { md: 'lock', filled: false },
  'magnifyingglass': { md: 'search', filled: false },
  'mic.slash': { md: 'mic_off', filled: false },
  'minus': { md: 'remove', filled: false },
  'music.note': { md: 'music_note', filled: false },
  'music.note.list': { md: 'queue_music', filled: false },
  'paperplane.fill': { md: 'send', filled: true },
  'pencil': { md: 'edit', filled: false },
  'person': { md: 'person', filled: false },
  'person.2': { md: 'group', filled: false },
  'person.2.fill': { md: 'group', filled: true },
  'photo': { md: 'image', filled: false },
  'pianokeys': { md: 'piano', filled: false },
  'plus': { md: 'add', filled: false },
  'plus.square.on.square': { md: 'library_add', filled: false },
  'questionmark.circle': { md: 'help', filled: false },
  'square.and.arrow.up': { md: 'share', filled: false },
  'square.and.pencil': { md: 'edit_square', filled: false },
  'star': { md: 'star', filled: false },
  'star.fill': { md: 'star', filled: true },
  'trash': { md: 'delete', filled: false },
  'tuningfork': { md: 'graphic_eq', filled: false },
  'wifi.slash': { md: 'wifi_off', filled: false },
  'wrench.and.screwdriver': { md: 'handyman', filled: false },
  'xmark': { md: 'close', filled: false },
  'xmark.circle.fill': { md: 'cancel', filled: true },
}
