-- =============================================================================
-- GraceChords: Song search variants for @gracechords_bot (2026-05-21)
-- Bot DMs send free-text song titles. The bot's /api/bot/songs/search endpoint
-- needs to match "King of Kings (Majesty)" from either "king of kings" or
-- "majesty", and either side of a "Holy / Santo" slash split. Variants are
-- generated by a trigger so newly-added songs become searchable with zero
-- manual work; existing rows are backfilled at migration time.
-- =============================================================================

create extension if not exists pg_trgm;

alter table public.songs
  add column if not exists search_titles text[] not null default '{}';

-- ---------------------------------------------------------------------------
-- 1. Variant generator
-- ---------------------------------------------------------------------------
create or replace function public.songs_compute_search_titles(t text)
returns text[]
language plpgsql
immutable
set search_path = public, pg_temp
as $$
declare
  variants       text[] := array[]::text[];
  base           text;
  paren_inner    text;
  paren_stripped text;
  half           text;
begin
  if t is null then
    return '{}';
  end if;

  base := regexp_replace(lower(trim(t)), '\s+', ' ', 'g');
  if base = '' then
    return '{}';
  end if;

  variants := array_append(variants, base);

  -- "Title (Subtitle)" → also "subtitle" and "title"
  paren_inner    := substring(base from '\(([^)]+)\)');
  paren_stripped := regexp_replace(base, '\s*\([^)]*\)\s*', ' ', 'g');
  paren_stripped := regexp_replace(trim(paren_stripped), '\s+', ' ', 'g');

  if paren_inner is not null then
    variants := array_append(variants, trim(paren_inner));
  end if;
  if paren_stripped <> base and paren_stripped <> '' then
    variants := array_append(variants, paren_stripped);
  end if;

  -- Slash split: run on both the original and the paren-stripped form
  foreach half in array regexp_split_to_array(coalesce(paren_stripped, base), '\s*/\s*') loop
    if length(trim(half)) > 0 then
      variants := array_append(variants, trim(half));
    end if;
  end loop;
  if paren_stripped is not null and paren_stripped <> base then
    foreach half in array regexp_split_to_array(base, '\s*/\s*') loop
      if length(trim(half)) > 0 then
        variants := array_append(variants, trim(half));
      end if;
    end loop;
  end if;

  return (
    select coalesce(array_agg(distinct v order by v), '{}')
      from unnest(variants) v
     where length(v) > 0
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- 2. Trigger
-- ---------------------------------------------------------------------------
create or replace function public.songs_search_titles_refresh()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  new.search_titles := public.songs_compute_search_titles(new.title);
  return new;
end;
$$;

drop trigger if exists trg_songs_search_titles on public.songs;
create trigger trg_songs_search_titles
  before insert or update of title on public.songs
  for each row execute function public.songs_search_titles_refresh();

-- ---------------------------------------------------------------------------
-- 3. Backfill existing rows
-- ---------------------------------------------------------------------------
update public.songs
   set search_titles = public.songs_compute_search_titles(title)
 where title is not null;

-- ---------------------------------------------------------------------------
-- 4. Trigram index for fuzzy similarity()
-- ---------------------------------------------------------------------------
create index if not exists songs_search_titles_trgm_idx
  on public.songs using gin (search_titles gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- 5. Bot-facing search RPC
-- ---------------------------------------------------------------------------
-- Returns up to `limit_count` candidates ordered by best similarity across
-- the song's title variants. Score in [0,1]; 1.0 = exact match. The bot
-- treats >= 0.9 as auto-pick and presents disambiguation otherwise.
create or replace function public.bot_search_songs(q text, limit_count integer default 8)
returns table (
  id           uuid,
  slug         text,
  title        text,
  default_key  text,
  artist       text,
  score        real
)
language sql
stable
set search_path = public, pg_temp
as $$
  with q_norm as (
    select regexp_replace(lower(trim(coalesce(q, ''))), '\s+', ' ', 'g') as q
  )
  select s.id,
         s.slug,
         s.title,
         s.default_key,
         s.artist,
         max(similarity(v, qn.q))::real as score
    from public.songs s
         cross join q_norm qn
         left join lateral unnest(s.search_titles) v on true
   where s.is_deleted = false
     and qn.q <> ''
     and v is not null
     and similarity(v, qn.q) >= 0.2
   group by s.id, s.slug, s.title, s.default_key, s.artist
   order by score desc, s.title asc
   limit greatest(1, coalesce(limit_count, 8));
$$;

grant execute on function public.bot_search_songs(text, integer) to anon, authenticated, service_role;
