-- =============================================================================
-- GraceChords: Song search variants for @gracechords_bot (2026-05-21)
-- Bot DMs send free-text song titles. The bot's /api/bot/songs/search endpoint
-- needs to match "King of Kings (Majesty)" from either "king of kings" or
-- "majesty", and either side of a "Holy / Santo" slash split. Variants are
-- generated by a trigger so newly-added songs become searchable with zero
-- manual work; existing rows are backfilled at migration time.
--
-- Design note: pg_trgm's gin_trgm_ops operator class only accepts scalar
-- text, not text[]. We therefore keep the array for clarity/debugging AND
-- derive a newline-joined `search_text` column that we index. The RPC
-- scores with word_similarity() over that concatenated text — equivalent to
-- picking the best-matching variant per song.
--
-- This migration is idempotent and safe to re-run on partially-applied DBs.
-- =============================================================================

create extension if not exists pg_trgm;

alter table public.songs
  add column if not exists search_titles text[] not null default '{}';

alter table public.songs
  add column if not exists search_text text not null default '';

-- ---------------------------------------------------------------------------
-- 1. Variant generator
-- ---------------------------------------------------------------------------
create or replace function public.songs_compute_search_titles(t text)
returns text[]
language plpgsql
immutable
set search_path = public, pg_temp
as $$
declare
  variants       text[] := array[]::text[];
  base           text;
  paren_inner    text;
  paren_stripped text;
  half           text;
begin
  if t is null then
    return '{}';
  end if;

  base := regexp_replace(lower(trim(t)), '\s+', ' ', 'g');
  if base = '' then
    return '{}';
  end if;

  variants := array_append(variants, base);

  -- "Title (Subtitle)" → also "subtitle" and "title"
  paren_inner    := substring(base from '\(([^)]+)\)');
  paren_stripped := regexp_replace(base, '\s*\([^)]*\)\s*', ' ', 'g');
  paren_stripped := regexp_replace(trim(paren_stripped), '\s+', ' ', 'g');

  if paren_inner is not null then
    variants := array_append(variants, trim(paren_inner));
  end if;
  if paren_stripped <> base and paren_stripped <> '' then
    variants := array_append(variants, paren_stripped);
  end if;

  -- Slash split: run on both the original and the paren-stripped form
  foreach half in array regexp_split_to_array(coalesce(paren_stripped, base), '\s*/\s*') loop
    if length(trim(half)) > 0 then
      variants := array_append(variants, trim(half));
    end if;
  end loop;
  if paren_stripped is not null and paren_stripped <> base then
    foreach half in array regexp_split_to_array(base, '\s*/\s*') loop
      if length(trim(half)) > 0 then
        variants := array_append(variants, trim(half));
      end if;
    end loop;
  end if;

  return (
    select coalesce(array_agg(distinct v order by v), '{}')
      from unnest(variants) v
     where length(v) > 0
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- 2. Trigger: maintain both columns from the title
-- ---------------------------------------------------------------------------
create or replace function public.songs_search_titles_refresh()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  new.search_titles := public.songs_compute_search_titles(new.title);
  new.search_text   := array_to_string(new.search_titles, E'\n');
  return new;
end;
$$;

drop trigger if exists trg_songs_search_titles on public.songs;
create trigger trg_songs_search_titles
  before insert or update of title on public.songs
  for each row execute function public.songs_search_titles_refresh();

-- ---------------------------------------------------------------------------
-- 3. Backfill (idempotent — updates both columns from current title)
-- ---------------------------------------------------------------------------
update public.songs
   set search_titles = public.songs_compute_search_titles(title),
       search_text   = array_to_string(public.songs_compute_search_titles(title), E'\n')
 where title is not null;

-- ---------------------------------------------------------------------------
-- 4. Trigram index on the scalar text column
-- ---------------------------------------------------------------------------
-- Drop the broken index from the original (failed) migration attempt if it
-- somehow got created.
drop index if exists public.songs_search_titles_trgm_idx;

create index if not exists songs_search_text_trgm_idx
  on public.songs using gin (search_text gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- 5. Bot-facing search RPC
-- ---------------------------------------------------------------------------
-- Returns up to `limit_count` candidates ordered by word_similarity score
-- between the query and the song's joined variants. Score in [0,1]; 1.0 =
-- exact match against one of the variants. The bot treats >= 0.9 as
-- auto-pick and presents disambiguation otherwise.
create or replace function public.bot_search_songs(q text, limit_count integer default 8)
returns table (
  id           uuid,
  slug         text,
  title        text,
  default_key  text,
  artist       text,
  score        real
)
language sql
stable
set search_path = public, pg_temp
as $$
  with q_norm as (
    select regexp_replace(lower(trim(coalesce(q, ''))), '\s+', ' ', 'g') as q
  )
  select s.id,
         s.slug,
         s.title,
         s.default_key,
         s.artist,
         word_similarity(qn.q, s.search_text)::real as score
    from public.songs s
         cross join q_norm qn
   where s.is_deleted = false
     and qn.q <> ''
     and word_similarity(qn.q, s.search_text) >= 0.2
   order by score desc, s.title asc
   limit greatest(1, coalesce(limit_count, 8));
$$;

grant execute on function public.bot_search_songs(text, integer) to anon, authenticated, service_role;
