#!/usr/bin/env node
// Human-readable day-by-day plan: every date of the year with its M'Cheyne
// readings and the scripture reference of the devotional(s) assigned to it.
//
//   node analysis/build_daily_plan.mjs   -> analysis/out/daily-plan.md
//
// Reads out/schedule.json, out/devotionals.json and the M'Cheyne plan.
// Deterministic. Run build_schedule.mjs first.

import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseVerseReference, bookNumberToName } from '../packages/core/src/songs/verseRef.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT = join(HERE, 'out')

const schedule = JSON.parse(await readFile(join(OUT, 'schedule.json'), 'utf8'))
const devotionals = JSON.parse(await readFile(join(OUT, 'devotionals.json'), 'utf8'))
const plan = JSON.parse(await readFile(join(HERE, '../packages/core/src/bible/mcheyne.plan.json'), 'utf8'))

const devByKey = new Map(devotionals.map((d) => [d.key, d]))

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December']
const ABBR = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

/** Chapters a reading slot expands to -- used only to decide what to bold. */
function chaptersOf(reading) {
  const book = bookNumberToName(reading.book)
  const parsed = parseVerseReference(`${book} ${reading.ref}`)
  if (parsed.error || !parsed.segments?.length) return []
  return [...new Set(parsed.segments.map((s) => s.chapter))].map((c) => `${reading.book}:${c}`)
}

const L = []
const w = (s = '') => L.push(s)

w("# Daily Plan — M'Cheyne Readings with Spurgeon Devotionals")
w()
w("Every day of the year: the four M'Cheyne reading slots, and the scripture each")
w('paired devotional is built on.')
w()
w('**Every pairing here is a scripture match.** A devotional appears on a day only')
w("because its own text is drawn from a passage that day reads — the day reading")
w('Genesis 1 gets a devotional on Genesis 1:4. **Bold** marks which reading it')
w('matched.')
w()
w('Days with no matching devotional are left **open** rather than filled with')
w('something unrelated.')
w()
w("The code in the last column (e.g. `06-01-AM`) is the entry's identifier in")
w("Spurgeon's original *Morning and Evening*, kept only so it can be traced back to")
w('its source. It carries no meaning here — pairing ignores the original calendar')
w('date and the morning/evening split entirely.')
w()
w("The M'Cheyne plan runs 365 days and has no February 29, so that day is absent.")
w()
w('---')
w()

let curMonth = 0
let twoCount = 0
let openCount = 0
for (const entry of plan) {
  const month = Number(entry.mmdd.slice(0, 2))
  const day = Number(entry.mmdd.slice(2))
  const date = `${entry.mmdd.slice(0, 2)}-${entry.mmdd.slice(2)}`
  const slot = schedule[date]
  if (!slot) continue

  if (month !== curMonth) {
    curMonth = month
    w(`## ${MONTHS[month - 1]}`)
    w()
    w('| Date | M\'Cheyne Readings | Devotional Scripture | Source |')
    w('|---|---|---|---|')
  }

  const matched = new Set(slot.matches.map((m) => m.chapter).filter(Boolean))

  const readings = entry.readings.map((r) => {
    const book = bookNumberToName(r.book)
    const label = `${book} ${r.ref}`
    const hit = chaptersOf(r).some((c) => matched.has(`${book} ${c.split(':')[1]}`))
    return hit ? `**${label}**` : label
  }).join(' · ')

  if (slot.devotionals.length === 2) twoCount += 1
  if (slot.devotionals.length === 0) openCount += 1

  const refs = slot.devotionals.length
    ? slot.matches.map((m) => m.reference).join('<br>')
    : '_— open —_'
  const keys = slot.devotionals.map((k) => `\`${k}\``).join('<br>') || '—'

  w(`| ${ABBR[month - 1]} ${day} | ${readings} | ${refs} | ${keys} |`)

  const isLastOfMonth = plan.find((p) => Number(p.mmdd.slice(0, 2)) === month && Number(p.mmdd.slice(2)) === day + 1) === undefined
  if (isLastOfMonth) w()
}

w('---')
w()
w(`365 days · ${twoCount} with two devotionals · ${365 - twoCount - openCount} with one · ` +
  `${openCount} open · ${Object.values(schedule).flatMap((s) => s.devotionals).length} devotionals paired.`)
w()
w('Generated by `analysis/build_daily_plan.mjs` from `analysis/out/schedule.json`.')

await writeFile(join(OUT, 'daily-plan.md'), L.join('\n') + '\n', 'utf8')
console.log(`Wrote ${join(OUT, 'daily-plan.md')} — 365 days, ${twoCount} with two devotionals`)
