name: Wiki Sync

on:
  push:
    branches: [ main ]
    # Only run when wiki-related files change
    paths:
      - 'public/wiki/**'
      - 'scripts/syncWiki.mjs'
      - '.github/workflows/wiki-sync.yml'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Sync to GitHub Wiki
        if: ${{ hashFiles('public/wiki/**') != '' }}
        run: node scripts/syncWiki.mjs
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          WIKI_PUSH_TOKEN: ${{ secrets.WIKI_PUSH_TOKEN }}
      - name: Build site into /docs
        run: npm run build
        env:
          VITE_COMMIT_SHA: ${{ github.sha }}
      - name: Commit and push /docs
        shell: bash
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Stage only docs so tracked node_modules changes don't interfere
          git add -A docs || true
          if git diff --cached --quiet; then
            echo "No changes to docs to commit"
            exit 0
          fi
          git commit -m "Build: $GITHUB_SHA (after wiki sync)"
          git push
