name: Sync Wiki

on:
  push:
    branches: [main]
    paths:
      - 'public/wiki/**'
      - '.github/workflows/wiki-sync.yml'
      - 'scripts/syncWiki.mjs'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: node scripts/syncWiki.mjs
        env:
          WIKI_PUSH_TOKEN: ${{ secrets.WIKI_PUSH_TOKEN }}
